# type: ignore
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dtsdb/schema.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dtsdb/schema.proto',
  package='dtsdb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x64tsdb/schema.proto\x12\x05\x64tsdb\x1a google/protobuf/descriptor.proto\"\"\n\x11\x44tsdbFieldOptions\x12\r\n\x05merge\x18\x02 \x01(\t\"\x15\n\x13\x44tsdbMessageOptions:H\n\x05\x66ield\x12\x1d.google.protobuf.FieldOptions\x18\xd0\x86\x03 \x01(\x0b\x32\x18.dtsdb.DtsdbFieldOptions:L\n\x05table\x12\x1f.google.protobuf.MessageOptions\x18\xd0\x86\x03 \x01(\x0b\x32\x1a.dtsdb.DtsdbMessageOptions'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


FIELD_FIELD_NUMBER = 50000
field = _descriptor.FieldDescriptor(
  name='field', full_name='dtsdb.field', index=0,
  number=50000, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
TABLE_FIELD_NUMBER = 50000
table = _descriptor.FieldDescriptor(
  name='table', full_name='dtsdb.table', index=1,
  number=50000, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)


_DTSDBFIELDOPTIONS = _descriptor.Descriptor(
  name='DtsdbFieldOptions',
  full_name='dtsdb.DtsdbFieldOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='merge', full_name='dtsdb.DtsdbFieldOptions.merge', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=97,
)


_DTSDBMESSAGEOPTIONS = _descriptor.Descriptor(
  name='DtsdbMessageOptions',
  full_name='dtsdb.DtsdbMessageOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['DtsdbFieldOptions'] = _DTSDBFIELDOPTIONS
DESCRIPTOR.message_types_by_name['DtsdbMessageOptions'] = _DTSDBMESSAGEOPTIONS
DESCRIPTOR.extensions_by_name['field'] = field
DESCRIPTOR.extensions_by_name['table'] = table
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DtsdbFieldOptions = _reflection.GeneratedProtocolMessageType('DtsdbFieldOptions', (_message.Message,), {
  'DESCRIPTOR' : _DTSDBFIELDOPTIONS,
  '__module__' : 'dtsdb.schema_pb2'
  # @@protoc_insertion_point(class_scope:dtsdb.DtsdbFieldOptions)
  })
_sym_db.RegisterMessage(DtsdbFieldOptions)

DtsdbMessageOptions = _reflection.GeneratedProtocolMessageType('DtsdbMessageOptions', (_message.Message,), {
  'DESCRIPTOR' : _DTSDBMESSAGEOPTIONS,
  '__module__' : 'dtsdb.schema_pb2'
  # @@protoc_insertion_point(class_scope:dtsdb.DtsdbMessageOptions)
  })
_sym_db.RegisterMessage(DtsdbMessageOptions)

field.message_type = _DTSDBFIELDOPTIONS
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(field)
table.message_type = _DTSDBMESSAGEOPTIONS
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(table)

# @@protoc_insertion_point(module_scope)
