# type: ignore
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dtsdb/test.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dtsdb import schema_pb2 as dtsdb_dot_schema__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dtsdb/test.proto',
  package='dtsdb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x64tsdb/test.proto\x12\x05\x64tsdb\x1a\x12\x64tsdb/schema.proto\"H\n\x06Simple\x12\n\n\x02id\x18\x01 \x02(\t\x12 \n\nopt_string\x18\x02 \x01(\tB\x0c\x82\xb5\x18\x08\x12\x06latest\x12\x10\n\x08req_bool\x18\x03 \x02(\x08\"\xa8\x01\n\x06Nested\x12\n\n\x02id\x18\x01 \x02(\t\x12*\n\tselection\x18\x02 \x01(\x0e\x32\x17.dtsdb.Nested.Selection\x12\"\n\x05inner\x18\x03 \x01(\x0b\x32\x13.dtsdb.Nested.Inner\x1a\x1f\n\x05Inner\x12\n\n\x02\x66\x31\x18\x01 \x01(\t\x12\n\n\x02\x66\x32\x18\x02 \x02(\x05\"!\n\tSelection\x12\t\n\x05HELLO\x10\x00\x12\t\n\x05WORLD\x10\x01\"\x12\n\x04NoId:\n\x82\xb5\x18\x06\n\x04NoId\"\xbc\x02\n\tMergeTest\x12\n\n\x02id\x18\x01 \x02(\t\x12\x1c\n\x07s_error\x18\x02 \x01(\tB\x0b\x82\xb5\x18\x07\x12\x05\x65rror\x12\x1e\n\x08s_latest\x18\x03 \x01(\tB\x0c\x82\xb5\x18\x08\x12\x06latest\x12 \n\x0br_i32_error\x18\x14 \x03(\x05\x42\x0b\x82\xb5\x18\x07\x12\x05\x65rror\x12%\n\x0cr_i32_sunion\x18\x15 \x03(\x05\x42\x0f\x82\xb5\x18\x0b\x12\tset_union\x12&\n\x0cr_i32_lunion\x18\x16 \x03(\x05\x42\x10\x82\xb5\x18\x0c\x12\nlist_union\x12\x44\n\tm_si32_ul\x18( \x03(\x0b\x32\x1d.dtsdb.MergeTest.MSi32UlEntryB\x12\x82\xb5\x18\x0e\x12\x0cunion_latest\x1a.\n\x0cMSi32UlEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01'
  ,
  dependencies=[dtsdb_dot_schema__pb2.DESCRIPTOR,])



_NESTED_SELECTION = _descriptor.EnumDescriptor(
  name='Selection',
  full_name='dtsdb.Nested.Selection',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HELLO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WORLD', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=257,
  serialized_end=290,
)
_sym_db.RegisterEnumDescriptor(_NESTED_SELECTION)


_SIMPLE = _descriptor.Descriptor(
  name='Simple',
  full_name='dtsdb.Simple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dtsdb.Simple.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opt_string', full_name='dtsdb.Simple.opt_string', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202\265\030\010\022\006latest', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='req_bool', full_name='dtsdb.Simple.req_bool', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=119,
)


_NESTED_INNER = _descriptor.Descriptor(
  name='Inner',
  full_name='dtsdb.Nested.Inner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='f1', full_name='dtsdb.Nested.Inner.f1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='f2', full_name='dtsdb.Nested.Inner.f2', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=255,
)

_NESTED = _descriptor.Descriptor(
  name='Nested',
  full_name='dtsdb.Nested',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dtsdb.Nested.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='selection', full_name='dtsdb.Nested.selection', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inner', full_name='dtsdb.Nested.inner', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_NESTED_INNER, ],
  enum_types=[
    _NESTED_SELECTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=290,
)


_NOID = _descriptor.Descriptor(
  name='NoId',
  full_name='dtsdb.NoId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\202\265\030\006\n\004NoId',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=310,
)


_MERGETEST_MSI32ULENTRY = _descriptor.Descriptor(
  name='MSi32UlEntry',
  full_name='dtsdb.MergeTest.MSi32UlEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='dtsdb.MergeTest.MSi32UlEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='dtsdb.MergeTest.MSi32UlEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=583,
  serialized_end=629,
)

_MERGETEST = _descriptor.Descriptor(
  name='MergeTest',
  full_name='dtsdb.MergeTest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dtsdb.MergeTest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='s_error', full_name='dtsdb.MergeTest.s_error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202\265\030\007\022\005error', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='s_latest', full_name='dtsdb.MergeTest.s_latest', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202\265\030\010\022\006latest', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='r_i32_error', full_name='dtsdb.MergeTest.r_i32_error', index=3,
      number=20, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202\265\030\007\022\005error', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='r_i32_sunion', full_name='dtsdb.MergeTest.r_i32_sunion', index=4,
      number=21, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202\265\030\013\022\tset_union', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='r_i32_lunion', full_name='dtsdb.MergeTest.r_i32_lunion', index=5,
      number=22, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202\265\030\014\022\nlist_union', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_si32_ul', full_name='dtsdb.MergeTest.m_si32_ul', index=6,
      number=40, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202\265\030\016\022\014union_latest', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MERGETEST_MSI32ULENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=629,
)

_NESTED_INNER.containing_type = _NESTED
_NESTED.fields_by_name['selection'].enum_type = _NESTED_SELECTION
_NESTED.fields_by_name['inner'].message_type = _NESTED_INNER
_NESTED_SELECTION.containing_type = _NESTED
_MERGETEST_MSI32ULENTRY.containing_type = _MERGETEST
_MERGETEST.fields_by_name['m_si32_ul'].message_type = _MERGETEST_MSI32ULENTRY
DESCRIPTOR.message_types_by_name['Simple'] = _SIMPLE
DESCRIPTOR.message_types_by_name['Nested'] = _NESTED
DESCRIPTOR.message_types_by_name['NoId'] = _NOID
DESCRIPTOR.message_types_by_name['MergeTest'] = _MERGETEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Simple = _reflection.GeneratedProtocolMessageType('Simple', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLE,
  '__module__' : 'dtsdb.test_pb2'
  # @@protoc_insertion_point(class_scope:dtsdb.Simple)
  })
_sym_db.RegisterMessage(Simple)

Nested = _reflection.GeneratedProtocolMessageType('Nested', (_message.Message,), {

  'Inner' : _reflection.GeneratedProtocolMessageType('Inner', (_message.Message,), {
    'DESCRIPTOR' : _NESTED_INNER,
    '__module__' : 'dtsdb.test_pb2'
    # @@protoc_insertion_point(class_scope:dtsdb.Nested.Inner)
    })
  ,
  'DESCRIPTOR' : _NESTED,
  '__module__' : 'dtsdb.test_pb2'
  # @@protoc_insertion_point(class_scope:dtsdb.Nested)
  })
_sym_db.RegisterMessage(Nested)
_sym_db.RegisterMessage(Nested.Inner)

NoId = _reflection.GeneratedProtocolMessageType('NoId', (_message.Message,), {
  'DESCRIPTOR' : _NOID,
  '__module__' : 'dtsdb.test_pb2'
  # @@protoc_insertion_point(class_scope:dtsdb.NoId)
  })
_sym_db.RegisterMessage(NoId)

MergeTest = _reflection.GeneratedProtocolMessageType('MergeTest', (_message.Message,), {

  'MSi32UlEntry' : _reflection.GeneratedProtocolMessageType('MSi32UlEntry', (_message.Message,), {
    'DESCRIPTOR' : _MERGETEST_MSI32ULENTRY,
    '__module__' : 'dtsdb.test_pb2'
    # @@protoc_insertion_point(class_scope:dtsdb.MergeTest.MSi32UlEntry)
    })
  ,
  'DESCRIPTOR' : _MERGETEST,
  '__module__' : 'dtsdb.test_pb2'
  # @@protoc_insertion_point(class_scope:dtsdb.MergeTest)
  })
_sym_db.RegisterMessage(MergeTest)
_sym_db.RegisterMessage(MergeTest.MSi32UlEntry)


_SIMPLE.fields_by_name['opt_string']._options = None
_NOID._options = None
_MERGETEST_MSI32ULENTRY._options = None
_MERGETEST.fields_by_name['s_error']._options = None
_MERGETEST.fields_by_name['s_latest']._options = None
_MERGETEST.fields_by_name['r_i32_error']._options = None
_MERGETEST.fields_by_name['r_i32_sunion']._options = None
_MERGETEST.fields_by_name['r_i32_lunion']._options = None
_MERGETEST.fields_by_name['m_si32_ul']._options = None
# @@protoc_insertion_point(module_scope)
