# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


class Path(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Component(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        class Repeated(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            field = ... # type: typing___Text
            index = ... # type: builtin___int

            def __init__(self,
                *,
                field : typing___Optional[typing___Text] = None,
                index : typing___Optional[builtin___int] = None,
                ) -> None: ...
            if sys.version_info >= (3,):
                @classmethod
                def FromString(cls, s: builtin___bytes) -> Path.Component.Repeated: ...
            else:
                @classmethod
                def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Path.Component.Repeated: ...
            def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
            def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
            def HasField(self, field_name: typing_extensions___Literal[u"field",b"field",u"index",b"index"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"field",b"field",u"index",b"index"]) -> None: ...
        global___Repeated = Repeated

        class Map(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            field = ... # type: typing___Text
            key = ... # type: typing___Text

            def __init__(self,
                *,
                field : typing___Optional[typing___Text] = None,
                key : typing___Optional[typing___Text] = None,
                ) -> None: ...
            if sys.version_info >= (3,):
                @classmethod
                def FromString(cls, s: builtin___bytes) -> Path.Component.Map: ...
            else:
                @classmethod
                def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Path.Component.Map: ...
            def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
            def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
            def HasField(self, field_name: typing_extensions___Literal[u"field",b"field",u"key",b"key"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"field",b"field",u"key",b"key"]) -> None: ...
        global___Map = Map

        normal_field = ... # type: typing___Text

        @property
        def repeated_field(self) -> global___Path.Component.Repeated: ...

        @property
        def map_field(self) -> global___Path.Component.Map: ...

        def __init__(self,
            *,
            normal_field : typing___Optional[typing___Text] = None,
            repeated_field : typing___Optional[global___Path.Component.Repeated] = None,
            map_field : typing___Optional[global___Path.Component.Map] = None,
            ) -> None: ...
        if sys.version_info >= (3,):
            @classmethod
            def FromString(cls, s: builtin___bytes) -> Path.Component: ...
        else:
            @classmethod
            def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Path.Component: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"map_field",b"map_field",u"normal_field",b"normal_field",u"repeated_field",b"repeated_field",u"type",b"type"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"map_field",b"map_field",u"normal_field",b"normal_field",u"repeated_field",b"repeated_field",u"type",b"type"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions___Literal[u"type",b"type"]) -> typing_extensions___Literal["normal_field","repeated_field","map_field"]: ...
    global___Component = Component


    @property
    def components(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[global___Path.Component]: ...

    def __init__(self,
        *,
        components : typing___Optional[typing___Iterable[global___Path.Component]] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Path: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Path: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"components",b"components"]) -> None: ...
global___Path = Path
