# type: ignore
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dtsdb/protodb/path.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dtsdb/protodb/path.proto',
  package='dtsdb.protodb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x64tsdb/protodb/path.proto\x12\rdtsdb.protodb\"\xae\x02\n\x04Path\x12\x31\n\ncomponents\x18\x01 \x03(\x0b\x32\x1d.dtsdb.protodb.Path.Component\x1a\xf2\x01\n\tComponent\x12\x16\n\x0cnormal_field\x18\x01 \x01(\tH\x00\x12@\n\x0erepeated_field\x18\x02 \x01(\x0b\x32&.dtsdb.protodb.Path.Component.RepeatedH\x00\x12\x36\n\tmap_field\x18\x03 \x01(\x0b\x32!.dtsdb.protodb.Path.Component.MapH\x00\x1a(\n\x08Repeated\x12\r\n\x05\x66ield\x18\x01 \x02(\t\x12\r\n\x05index\x18\x02 \x02(\r\x1a!\n\x03Map\x12\r\n\x05\x66ield\x18\x01 \x02(\t\x12\x0b\n\x03key\x18\x02 \x02(\tB\x06\n\x04type'
)




_PATH_COMPONENT_REPEATED = _descriptor.Descriptor(
  name='Repeated',
  full_name='dtsdb.protodb.Path.Component.Repeated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='dtsdb.protodb.Path.Component.Repeated.field', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='dtsdb.protodb.Path.Component.Repeated.index', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=303,
)

_PATH_COMPONENT_MAP = _descriptor.Descriptor(
  name='Map',
  full_name='dtsdb.protodb.Path.Component.Map',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='dtsdb.protodb.Path.Component.Map.field', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='dtsdb.protodb.Path.Component.Map.key', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=338,
)

_PATH_COMPONENT = _descriptor.Descriptor(
  name='Component',
  full_name='dtsdb.protodb.Path.Component',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='normal_field', full_name='dtsdb.protodb.Path.Component.normal_field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='repeated_field', full_name='dtsdb.protodb.Path.Component.repeated_field', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='map_field', full_name='dtsdb.protodb.Path.Component.map_field', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PATH_COMPONENT_REPEATED, _PATH_COMPONENT_MAP, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='dtsdb.protodb.Path.Component.type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=104,
  serialized_end=346,
)

_PATH = _descriptor.Descriptor(
  name='Path',
  full_name='dtsdb.protodb.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='components', full_name='dtsdb.protodb.Path.components', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PATH_COMPONENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=346,
)

_PATH_COMPONENT_REPEATED.containing_type = _PATH_COMPONENT
_PATH_COMPONENT_MAP.containing_type = _PATH_COMPONENT
_PATH_COMPONENT.fields_by_name['repeated_field'].message_type = _PATH_COMPONENT_REPEATED
_PATH_COMPONENT.fields_by_name['map_field'].message_type = _PATH_COMPONENT_MAP
_PATH_COMPONENT.containing_type = _PATH
_PATH_COMPONENT.oneofs_by_name['type'].fields.append(
  _PATH_COMPONENT.fields_by_name['normal_field'])
_PATH_COMPONENT.fields_by_name['normal_field'].containing_oneof = _PATH_COMPONENT.oneofs_by_name['type']
_PATH_COMPONENT.oneofs_by_name['type'].fields.append(
  _PATH_COMPONENT.fields_by_name['repeated_field'])
_PATH_COMPONENT.fields_by_name['repeated_field'].containing_oneof = _PATH_COMPONENT.oneofs_by_name['type']
_PATH_COMPONENT.oneofs_by_name['type'].fields.append(
  _PATH_COMPONENT.fields_by_name['map_field'])
_PATH_COMPONENT.fields_by_name['map_field'].containing_oneof = _PATH_COMPONENT.oneofs_by_name['type']
_PATH.fields_by_name['components'].message_type = _PATH_COMPONENT
DESCRIPTOR.message_types_by_name['Path'] = _PATH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), {

  'Component' : _reflection.GeneratedProtocolMessageType('Component', (_message.Message,), {

    'Repeated' : _reflection.GeneratedProtocolMessageType('Repeated', (_message.Message,), {
      'DESCRIPTOR' : _PATH_COMPONENT_REPEATED,
      '__module__' : 'dtsdb.protodb.path_pb2'
      # @@protoc_insertion_point(class_scope:dtsdb.protodb.Path.Component.Repeated)
      })
    ,

    'Map' : _reflection.GeneratedProtocolMessageType('Map', (_message.Message,), {
      'DESCRIPTOR' : _PATH_COMPONENT_MAP,
      '__module__' : 'dtsdb.protodb.path_pb2'
      # @@protoc_insertion_point(class_scope:dtsdb.protodb.Path.Component.Map)
      })
    ,
    'DESCRIPTOR' : _PATH_COMPONENT,
    '__module__' : 'dtsdb.protodb.path_pb2'
    # @@protoc_insertion_point(class_scope:dtsdb.protodb.Path.Component)
    })
  ,
  'DESCRIPTOR' : _PATH,
  '__module__' : 'dtsdb.protodb.path_pb2'
  # @@protoc_insertion_point(class_scope:dtsdb.protodb.Path)
  })
_sym_db.RegisterMessage(Path)
_sym_db.RegisterMessage(Path.Component)
_sym_db.RegisterMessage(Path.Component.Repeated)
_sym_db.RegisterMessage(Path.Component.Map)


# @@protoc_insertion_point(module_scope)
